# -*- coding: utf-8 -*-
"""Predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z7g7HkbLTrBtLr8SKOz0Dox1BoUY3lj6

## LOAD MODEL
"""

from keras.models import load_model
mymodel = load_model('flowers_applications_fit.h5')

"""## IMAGE PREDICT"""

#Don't forget to arrange the file paths for yourself !!

from PIL import Image               
from IPython.display import display 
from keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np
import os

directory = r'flowers/Try'

for filename in os.listdir(directory):
  img = image.load_img("./flowers/Try/" + filename, target_size=(224,224))
  display(img)
  img = np.asarray(img)
  img = np.expand_dims(img, axis=0)
  output = mymodel.predict(img)[0]

  for i in range(4):
    if output[0] > output[i]:
      result = "Daisy"
    elif output[1] > output[i]:
      result = "Dandelion"
    elif output[2] > output[i]:
      result = "Rose"
    elif output[3] > output[i]:
      result = "Sunflower"
    elif output[4] > output[i]:
      result = "Tupil"
  
  print(result)
  print("------------------------")

